class ChecklistModel {
  constructor(
    public venueId: any,
    public userId: any,
    public version: string,
    public question1?: string,
    public question2?: string,
    public question3?: string,
    public question4?: string,
    public question5?: string,
    public question6?: string,
    public question7?: string,
    public question7Date?: any,
    public question8?: string,
    public question9?: string,
    public question9Person?: string,
    public question10?: string,
    public question10Person?: string,
    public question11?: string,
    public question11Capacity?: any,
    public question11Date?: any,
    public question12?: string,
    public question12Date?: any,
    public question13?: string,
    public question13Date?: any,
    public question14?: string,
    public question14Date?: any,
    public question15?: string,
    public question15Date?: any,
    public timestamp?: any,
    public ipAddress?: string,
    public _id?: string,
  ) { }
}

class FormChecklistModel {
  constructor(
    public userId: string,
    public venueId: string,
    public version: string,
    public question1?: any,
    public question2?: any,
    public question3?: any,
    public question4?: any,
    public question5?: any,
    public question6?: any,
    public question7?: any,
    public question7Date?: any,
    public question8?: any,
    public question9?: any,
    public question9Person?: string,
    public question10?: any,
    public question10Person?: string,
    public question11?: any,
    public question11Capacity?: any,
    public question11Date?: any,
    public question12?: any,
    public question12Date?: any,
    public question13?: any,
    public question13Date?: any,
    public question14?: any,
    public question14Date?: any,
    public question15?: any,
    public question15Date?: any,
  ) { }
}

export { ChecklistModel, FormChecklistModel };